#!/bin/dash

# if no .shrug directory
if test ! -d ".shrug"; then
	echo "shrug-commit: error: no .shrug directory containing shrug repository exists"
	exit 1
elif test "$#" = "0"; then
	echo "usage: shrug-commit [-a] -m commit-message"
	exit 1
fi
 
if test "$#" -eq 3 && test "$1" = "-a"; then
	for file in `ls .shrug/index`
	do
		# if file in index exists in current directory
		# remove the file from index and copy new version to index
		if test -f "$file"; then
			rm ".shrug/index/$file"
			cp "$file" ".shrug/index"			
		else
			#if file in index does not exist in working dir
			# then remove from index before commit
			rm ".shrug/index/$file"
		fi
	done
fi

# if index is empty and first commit
if test "`ls .shrug/index`" = "" && test ! -f ".shrug/log"; then
	echo "nothing to commit"
	exit 0
#if first comiit
elif test ! -f ".shrug/log"; then
	touch .shrug/log
	new_version=0
else
	new_version=`cat .shrug/log | wc -l`
	current_version=$(( $new_version-1 ))
	same=0
	for file in `ls .shrug/commits/$current_version`
	do	# if a file from last commit is not present in the index
		# as a file has been removed a new commit needs to be made
		if test ! -f ".shrug/index/$file"; then
			same=1
			break
		fi
	done
	for file in `ls .shrug/index`
	do
		#echo $file
		# if index file does not exist in current version
		if test ! -f ".shrug/commits/$current_version/$file"; then
			#echo "does not exist"
			# move to make commit as there are changes
			same=1
			break
		else
			# if index file does exist check if its different from last commit
			diff=`diff .shrug/commits/$current_version/$file .shrug/index/$file`
			if test "$diff" != ""; then
				#echo "different"
				# move to make commit as there are changes
				same=1
				break
			fi
			# 
			
		fi
	done
	# nothing has changed since last commit in index
	#echo $same
	if test "$same" = "0"; then
		echo "nothing to commit"
		exit 1
	fi
        
fi
# make new commit folder
mkdir .shrug/commits/$new_version

# copy all files from index to commit folder
if test "`ls .shrug/index`" != ""; then
	cp .shrug/index/* .shrug/commits/$new_version
fi

# append to log
if test "$#" -eq 3; then
	echo "$new_version $3" >> .shrug/log
	#cat .shrug/log
else
	echo "$new_version $2" >> .shrug/log
fi

# echo output to user 
echo "Committed as commit $new_version"
