#!/bin/dash

if test -d ".shrug"; then
	echo "shrug-init: error: .shrug already exists"
	exit 1
else
	mkdir .shrug
	echo "Initialized empty shrug repository in .shrug"
	# make index
	mkdir .shrug/index
	#touch .shrug/log
	mkdir .shrug/commits
fi

